<?php

return [
    [
        'slug' => 'automotive-battery-pro',
        'name' => 'Automotive Battery Pro',
        'category' => 'Automotive Batteries',
        'badge' => 'Fast Start',
        'image' => 'images/products/automotive-battery-pro.jpg',
        'alt' => 'Premium automotive battery product render with glossy black casing and metal terminals',
        'excerpt' => 'High-cranking performance and dependable start-up power for cars and utility vehicles.',
        'description' => 'Engineered for strong ignition response, stable current delivery, and reliable day-to-day vehicle performance in urban and heavy-duty driving conditions.',
        'hero_copy' => 'Built for crisp ignition, consistent output, and confident starts in every season.',
        'price' => 'From Rs. 12,499',
        'capacity' => '12V / 75Ah',
        'backup' => 'High-cranking start power',
        'warranty' => '48-month support',
        'applications' => ['Passenger cars', 'SUVs', 'Utility vehicles'],
        'features' => ['Fast charging acceptance', 'Vibration-resistant body', 'Low-maintenance design'],
    ],
    [
        'slug' => 'inverter-backup-max',
        'name' => 'Inverter Backup Max',
        'category' => 'Inverter Batteries',
        'badge' => 'Home Backup',
        'image' => 'images/products/inverter-backup-max.jpg',
        'alt' => 'Premium inverter battery product render with tall glossy body and soft studio lighting',
        'excerpt' => 'Long-lasting backup battery engineered for homes, offices, and uninterrupted power support.',
        'description' => 'A dependable deep-cycle battery made for extended backup durations, fast recharge recovery, and stable support during grid fluctuations.',
        'hero_copy' => 'Silent, efficient backup power designed for homes and business-critical spaces.',
        'price' => 'From Rs. 18,999',
        'capacity' => '12V / 180Ah',
        'backup' => 'Long-duration deep cycle',
        'warranty' => '60-month support',
        'applications' => ['Homes', 'Retail outlets', 'Office backup systems'],
        'features' => ['Deep-discharge recovery', 'Long service life', 'Low water loss design'],
    ],
    [
        'slug' => 'solar-storage-plus',
        'name' => 'Solar Storage Plus',
        'category' => 'Solar Batteries',
        'badge' => 'Eco Storage',
        'image' => 'images/products/solar-storage-plus.jpg',
        'alt' => 'Premium solar storage battery render with futuristic black body and subtle green-blue lighting',
        'excerpt' => 'Efficient energy storage to maximize solar system output and extend usable power.',
        'description' => 'Optimized for renewable setups that demand clean storage, cycle stability, and smarter energy retention for everyday solar use.',
        'hero_copy' => 'Capture more solar energy and keep clean power available long after sunset.',
        'price' => 'From Rs. 29,499',
        'capacity' => '48V / 100Ah',
        'backup' => 'High-cycle energy storage',
        'warranty' => '72-month support',
        'applications' => ['Residential solar', 'Hybrid systems', 'Energy storage banks'],
        'features' => ['High cycle efficiency', 'Stable thermal behavior', 'Solar-ready charge profile'],
    ],
    [
        'slug' => 'industrial-power-cell',
        'name' => 'Industrial Power Cell',
        'category' => 'Industrial Batteries',
        'badge' => 'Heavy Duty',
        'image' => 'images/products/industrial-power-cell.jpg',
        'alt' => 'Heavy-duty industrial battery product render with reinforced matte-black casing',
        'excerpt' => 'Heavy-duty battery support for industrial operations, machinery, and critical systems.',
        'description' => 'Created for demanding industrial environments that require durable construction, output stability, and reliable support across continuous-use operations.',
        'hero_copy' => 'Industrial-grade power delivery with rugged protection for mission-critical systems.',
        'price' => 'From Rs. 34,999',
        'capacity' => '24V / 200Ah',
        'backup' => 'Continuous heavy-load support',
        'warranty' => '36-month support',
        'applications' => ['Machinery', 'Control rooms', 'Plant operations'],
        'features' => ['Reinforced housing', 'High-load endurance', 'Operational reliability'],
    ],
    [
        'slug' => 'tubular-reserve-xt',
        'name' => 'Tubular Reserve XT',
        'category' => 'Tubular Batteries',
        'badge' => 'Long Backup',
        'image' => 'images/products/tubular-reserve-xt.jpg',
        'alt' => 'Premium tubular battery render with sleek modern housing and cool blue highlights',
        'excerpt' => 'Robust deep-cycle battery designed for long backup durations and consistent output.',
        'description' => 'Purpose-built for reliable reserve capacity, steady voltage delivery, and dependable performance during longer outage windows.',
        'hero_copy' => 'Extended reserve power with dependable cycle life for uninterrupted comfort.',
        'price' => 'From Rs. 21,499',
        'capacity' => '12V / 220Ah',
        'backup' => 'Long-duration reserve output',
        'warranty' => '60-month support',
        'applications' => ['Residential backup', 'Small businesses', 'Inverter systems'],
        'features' => ['Deep-cycle plates', 'Long backup window', 'Consistent voltage profile'],
    ],
    [
        'slug' => 'ups-shield-battery',
        'name' => 'UPS Shield Battery',
        'category' => 'UPS Batteries',
        'badge' => 'Critical Load',
        'image' => 'images/products/ups-shield-battery.jpg',
        'alt' => 'Compact premium UPS battery render with clean industrial design and cool blue accents',
        'excerpt' => 'Stable backup support for servers, electronics, and sensitive systems requiring clean power.',
        'description' => 'Designed to support sensitive electronics with reliable reserve power, controlled output, and protection-friendly backup performance.',
        'hero_copy' => 'Clean, stable backup power for servers, devices, and high-value electronics.',
        'price' => 'From Rs. 16,999',
        'capacity' => '12V / 100Ah',
        'backup' => 'Instant backup response',
        'warranty' => '42-month support',
        'applications' => ['Server racks', 'Network rooms', 'Sensitive electronics'],
        'features' => ['Low-ripple delivery', 'Fast response profile', 'Compact deployment footprint'],
    ],
];
